version: '3.8'

services:
  compliance-service:
    build: .
    container_name: livhana-compliance-service
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - ENVIRONMENT=development
    volumes:
      - ./:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health').raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    labels:
      - "com.livhana.service=compliance"
      - "com.livhana.compliance=age21+nist+medical"

