apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: integration-service
  namespace: default
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: "true"
        run.googleapis.com/concurrency: "40"
    spec:
      serviceAccountName: integration-service@reggieanddrodispensary.iam.gserviceaccount.com
      containers:
        - image: gcr.io/$PROJECT/integration-service:$SERVICE
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
            - name: GCP_PROJECT_ID
              value: reggieanddrodispensary
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: "8080"
            - name: LIGHTSPEED_TOKEN
              valueFrom:
                secretKeyRef:
                  name: lightspeed-token-secret
                  key: credential
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url-secret
                  key: credential
          resources:
            limits:
              memory: 512Mi
              cpu: 1
            requests:
              memory: 256Mi
              cpu: 500m
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3
      timeoutSeconds: 60
      containerConcurrency: 40
      minScale: 1
      maxScale: 10
      ingress: internal-and-cloud-load-balancing
