apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: integration-service
  namespace: default
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: "true"
        run.googleapis.com/concurrency: "40"
    spec:
      serviceAccountName: integration-service@reggieanddrodispensary.iam.gserviceaccount.com
      containers:
        - image: gcr.io/reggieanddrodispensary/integration-service:latest
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: "8080"
          envFrom:
            - secretRef:
                name: lightspeed-token
          resources:
            limits:
              memory: 512Mi
              cpu: 1
      timeoutSeconds: 60
      containerConcurrency: 40
      ingress: internal-and-cloud-load-balancing
