version: '3.8'
services:
  frontend:
    build: ./frontend/vibe-cockpit
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:3005
    depends_on:
      - backend
      
  backend:
    build: ./backend/integration-service
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - REDIS_HOST=redis
    depends_on:
      - redis
      
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      
volumes:
  redis-data:
