version: '3.8'
services:
  # Frontend - Voice-First Cockpit
  frontend:
    build: ./frontend/vibe-cockpit
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://integration-service:3005
      - VITE_VOICE_API_URL=http://voice-service:8080
      - VITE_REASONING_API_URL=http://reasoning-gateway:8080
    depends_on:
      - integration-service
      - voice-service
      - reasoning-gateway
      
  # Integration Service - Legacy Backend Compatibility
  integration-service:
    build: ./backend/integration-service
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - REDIS_HOST=host.docker.internal
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
      
  # Voice Service - ElevenLabs TTS + Queue Management
  voice-service:
    build: ./backend/voice-service
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - REASONING_GATEWAY_BASE_URL=http://reasoning-gateway:8080/api/reasoning
      - REASONING_QUEUE_NAME=voice-mode-reasoning-jobs
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
    env_file:
      - .env
    network_mode: "host"
    depends_on:
      - reasoning-gateway
      
  # Reasoning Gateway - DeepSeek + Anthropic + OpenAI
  reasoning-gateway:
    build: ./backend/reasoning-gateway
    ports:
      - "4002:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    env_file:
      - .env
    network_mode: "host"
      
# Redis already running on host - using existing instance

# Last updated: 2025-10-29
