#!/bin/bash

# Self-Improvement Loop Cron Setup
# Sets up cron jobs for automated improvement cycles

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

echo "Setting up self-improvement cron jobs..."
echo "Project root: $PROJECT_ROOT"

# Check if cron is available
if ! command -v crontab &> /dev/null; then
    echo "ERROR: cron is not available on this system"
    exit 1
fi

# Create cron job entries
CRON_JOBS="
# Liv Hana Self-Improvement Loop
# Auto-generated by setup-cron.sh

# Daily: Analyze yesterday's interactions (runs at 2 AM)
0 2 * * * cd $PROJECT_ROOT/backend/reasoning-gateway && /usr/local/bin/node scripts/run-improvement-cycle.js --type=daily >> /var/log/livhana-improvement-daily.log 2>&1

# Weekly: Generate improvement proposals (runs Monday at 6 AM)
0 6 * * 1 cd $PROJECT_ROOT/backend/reasoning-gateway && /usr/local/bin/node scripts/run-improvement-cycle.js --type=weekly >> /var/log/livhana-improvement-weekly.log 2>&1

# Monthly: Major refactoring suggestions (runs 1st of month at 8 AM)
0 8 1 * * cd $PROJECT_ROOT/backend/reasoning-gateway && /usr/local/bin/node scripts/run-improvement-cycle.js --type=monthly >> /var/log/livhana-improvement-monthly.log 2>&1

# Hourly: Check for approved proposals and execute them
0 * * * * cd $PROJECT_ROOT/backend/reasoning-gateway && /usr/local/bin/node scripts/run-improvement-cycle.js --type=daily --auto-execute >> /var/log/livhana-improvement-auto.log 2>&1
"

# Backup existing crontab
echo "Backing up existing crontab..."
crontab -l > /tmp/crontab-backup-$(date +%Y%m%d-%H%M%S).txt 2>/dev/null || true

# Check if our cron jobs already exist
if crontab -l 2>/dev/null | grep -q "Liv Hana Self-Improvement Loop"; then
    echo "WARNING: Self-improvement cron jobs already exist"
    echo "Remove them manually with 'crontab -e' before running this script"
    exit 1
fi

# Add new cron jobs
(crontab -l 2>/dev/null || true; echo "$CRON_JOBS") | crontab -

echo "Cron jobs installed successfully!"
echo ""
echo "Installed schedules:"
echo "  - Daily analysis: 2 AM every day"
echo "  - Weekly proposals: 6 AM every Monday"
echo "  - Monthly refactoring: 8 AM on 1st of each month"
echo "  - Auto-execution: Every hour"
echo ""
echo "Logs will be written to:"
echo "  /var/log/livhana-improvement-*.log"
echo ""
echo "To view current cron jobs: crontab -l"
echo "To edit cron jobs: crontab -e"
echo "To remove cron jobs: crontab -r"
