apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: attribution-ledger
  namespace: default
  annotations:
    autoscaling.knative.dev/minScale: "0"
    autoscaling.knative.dev/maxScale: "5"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/liv-hana-sovereign/liv-hana-sovereign/attribution-ledger:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.5"
        env:
        - name: NODE_ENV
          value: "production"
        - name: COMPLIANCE_LEVEL
          value: "21+"
        - name: LEDGER_TYPE
          value: "attribution"
        - name: RETENTION_POLICY
          value: "30_days"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 3
      timeoutSeconds: 300
  traffic:
  - percent: 100
    latestRevision: true

# Last optimized: 2025-10-02
