name: Load secrets demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load secrets from 1Password
        uses: 1Password/load-secrets-action@v2
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          sign-in-address: reggiedro.1password.com
          secrets: |
            OPENAI_KEY=op://Liv Hana / Ops – Keys/openai-project/bearer
            GOOGLE_KEY=op://Liv Hana / Ops – Keys/google-domain/json

      - name: Confirm env (demo)
        run: echo "OpenAI key starts with: ${OPENAI_KEY:0:5}***"
